export const FLIGHTS_REQUEST = 'FLIGHTS_REQUEST';
export const FLIGHT_REQUEST_SUCCESS = 'FLIGHT_REQUEST_SUCCESS';
export const FLIGHT_REQUEST_FAIL = 'FLIGHT_REQUEST_FAIL';
export const FLIGHT_REQUEST_LOADING = 'FLIGHT_REQUEST_LOADING';