export const FLIGHTS_REQUEST = 'FLIGHTS_REQUEST';
export const FLIGHT_REQUEST_SUCCESS = 'FLIGHT_REQUEST_SUCCESS';
export const FLIGHT_REQUEST_FAIL = 'FLIGHT_REQUEST_FAIL';
export const FLIGHT_REQUEST_LOADING = 'FLIGHT_REQUEST_LOADING';

export const ADD_FLIGHT_DETAILS = 'ADD_FLIGHT_DETAILS';
export const ADD_FLIGHT_DETAILS_SUCCESS = 'ADD_FLIGHT_DETAILS_SUCCESS';

export const EDIT_FLIGHT_DETAILS = 'EDIT_FLIGHT_DETAILS';
export const EDIT_FLIGHT_DETAILS_SUCCESS = 'EDIT_FLIGHT_DETAILS_SUCCESS';

export const DELETE_FLIGHT_DETAILS = 'DELETE_FLIGHT_DETAILS';
export const DELETE_FLIGHT_DETAILS_SUCCESS = 'DELETE_FLIGHT_DETAILS_SUCCESS';